"""add_system_settings_table

Revision ID: 0a8be336eb20
Revises: 7fa2b40a0479
Create Date: 2026-01-05 09:32:18.548082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8be336eb20'
down_revision: Union[str, Sequence[str], None] = '7fa2b40a0479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings')),
    sa.UniqueConstraint('group_name', 'key', name='uq_system_settings_group_key')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_group_name'), ['group_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))
        batch_op.drop_index(batch_op.f('ix_system_settings_id'))
        batch_op.drop_index(batch_op.f('ix_system_settings_group_name'))

    op.drop_table('system_settings')
    # ### end Alembic commands ###
