"""add_group_indexes_and_constraints

Revision ID: 78103eb008a2
Revises: 12edbe79c712
Create Date: 2026-01-24 17:34:03.793554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78103eb008a2'
down_revision: Union[str, Sequence[str], None] = '12edbe79c712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_group_member', ['group_id', 'member_id'])

    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.create_index('ix_group_messages_group_id_create_time', ['group_id', 'create_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_group_messages_group_id_create_time')

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_constraint('uq_group_member', type_='unique')

    # ### end Alembic commands ###
