"""add_session_memory_fields

Revision ID: 7fa2b40a0479
Revises: df40a676419c
Create Date: 2026-01-04 19:41:01.674778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa2b40a0479'
down_revision: Union[str, Sequence[str], None] = 'df40a676419c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memory_generated', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_message_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_messages_friend_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_messages_friend_id'), ['friend_id'], unique=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_column('last_message_time')
        batch_op.drop_column('memory_generated')

    # ### end Alembic commands ###
