"""add_embedding_setting_table

Revision ID: df40a676419c
Revises: 2cab6e171efe
Create Date: 2026-01-04 16:12:26.691035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df40a676419c'
down_revision: Union[str, Sequence[str], None] = '2cab6e171efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding_provider', sa.String(), nullable=True),
    sa.Column('embedding_api_key', sa.String(), nullable=True),
    sa.Column('embedding_base_url', sa.String(), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('embedding_max_token_size', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_settings'))
    )
    with op.batch_alter_table('embedding_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embedding_settings_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embedding_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embedding_settings_id'))

    op.drop_table('embedding_settings')
    # ### end Alembic commands ###
